package:
  name: tass-core
  version: 0.9.0

source:
  path: ../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python >=3.10
    - selenium >=4.35.0
    - openpyxl
    - packaging
    - jsonschema