package:
  name: tass
  version: 0.1.0

source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >3.8
    - setuptools
    - pip
  run:
    - python >3.8
