package:
  name: tass-converter
  version: 0.8.0

source:
  path: ../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python >3.10
    - openpyxl
