package:
  name: tass-converter
  version: 0.10.0

source:
  path: ../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python >=3.10
    - openpyxl

extra:
  authors:
    - name: Dominic Parent
      email: dominic.parent@statcan.gc.ca
    - name: Tyler Desjardins
      email: josephgillestyler.desjardins@statcan.gc.ca
